#!/usr/bin/env python3
"""
Media Workflow Assistant - Local Production Helper

Runs on the person's own computer, alongside the browser application. It
detects an existing FFmpeg/FFprobe installation and performs local video
production (mixing described audio, muxing captions, final rendering,
FFprobe validation) that a browser page cannot do on its own.

Security model, by design:
  - Binds to 127.0.0.1 only. Never accessible from the network.
  - Never uses a shell (no shell=True, no string-concatenated commands).
    Every FFmpeg/FFprobe invocation is one of a small, fixed set of
    argument-list templates in run_ffmpeg_render() / run_ffprobe(). The
    client can select WHICH of those templates to run and supply asset
    IDs and simple booleans, but can never supply raw command-line
    arguments or an arbitrary path.
  - All file references from the client are opaque asset IDs generated by
    this server (uuid4), not client-supplied paths. Uploaded bytes are
    written under a single per-run temporary working directory; every
    file this server ever reads or writes stays inside that directory.
  - Rejects any request that is not one of the small set of endpoints
    below. There is no generic "run a command" endpoint.

Run with:  python production_helper.py
Requires only the Python standard library (Python 3.8+).
"""

import http.server
import json
import os
import shutil
import socketserver
import subprocess
import tempfile
import threading
import time
import uuid

HOST = "127.0.0.1"
PORT = 8788

WORKDIR = tempfile.mkdtemp(prefix="odd-production-")
ASSETS = {}   # assetId -> absolute path inside WORKDIR
JOBS = {}     # jobId -> {status, progress, message, outputAssetId, process}
LOCK = threading.Lock()

COMMON_WINDOWS_LOCATIONS = [
    r"C:\ffmpeg\bin",
    r"C:\Program Files\ffmpeg\bin",
    r"C:\Program Files (x86)\ffmpeg\bin",
    os.path.expanduser(r"~\AppData\Local\Microsoft\WinGet\Packages"),
    os.path.expanduser(r"~\Apps\ffmpeg\bin"),
    os.path.expanduser(r"~\Apps\SharedServices\ffmpeg\bin"),
]


def find_executable(name):
    """Look on PATH first, then a short list of common Windows install
    locations. Returns an absolute path or None. Never executes anything
    to search — only shutil.which() and os.path existence checks."""
    found = shutil.which(name)
    if found:
        return found
    exe_name = name + ".exe" if os.name == "nt" or not name.endswith(".exe") else name
    for folder in COMMON_WINDOWS_LOCATIONS:
        candidate = os.path.join(folder, exe_name)
        if os.path.isfile(candidate):
            return candidate
    return None


def probe_version(executable_path):
    """Runs `<executable> -version` (never through a shell) and returns the
    first line of output, or None if it fails."""
    if not executable_path:
        return None
    try:
        result = subprocess.run(
            [executable_path, "-version"],
            capture_output=True, text=True, timeout=5
        )
        first_line = (result.stdout or result.stderr or "").splitlines()
        return first_line[0].strip() if first_line else "Unknown version"
    except Exception:
        return None


STATE = {"ffmpeg": None, "ffprobe": None}


def detect_runtimes():
    ffmpeg_path = find_executable("ffmpeg")
    ffprobe_path = find_executable("ffprobe")
    STATE["ffmpeg"] = {"found": bool(ffmpeg_path), "path": ffmpeg_path, "version": probe_version(ffmpeg_path)}
    STATE["ffprobe"] = {"found": bool(ffprobe_path), "path": ffprobe_path, "version": probe_version(ffprobe_path)}


def run_ffprobe(path):
    """Fixed-template FFprobe call: inspect a known local file. No
    client-supplied arguments beyond which already-uploaded asset to
    inspect."""
    executable = STATE["ffprobe"]["path"]
    if not executable:
        raise RuntimeError("FFprobe was not detected on this computer.")
    args = [executable, "-v", "quiet", "-print_format", "json", "-show_format", "-show_streams", path]
    result = subprocess.run(args, capture_output=True, text=True, timeout=60)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or "FFprobe could not read that file.")
    return json.loads(result.stdout or "{}")


def build_render_args(ffmpeg_path, video_path, audio_path, captions_path, keep_original_audio, output_path):
    """The one, fixed render template. Every argument here is either a
    literal flag or a path already validated to live inside WORKDIR — never
    a raw string from the client."""
    args = [ffmpeg_path, "-y", "-i", video_path]
    input_index = 1
    audio_input_index = None
    captions_input_index = None
    if audio_path:
        args += ["-i", audio_path]
        audio_input_index = input_index
        input_index += 1
    if captions_path:
        args += ["-i", captions_path]
        captions_input_index = input_index
        input_index += 1

    args += ["-map", "0:v:0"]
    if audio_input_index is not None:
        args += ["-map", f"{audio_input_index}:a:0"]
        if keep_original_audio:
            args += ["-map", "0:a:0?"]
    else:
        args += ["-map", "0:a:0?"]
    if captions_input_index is not None:
        args += ["-map", f"{captions_input_index}:0"]

    args += ["-c:v", "copy", "-c:a", "aac"]
    if captions_input_index is not None:
        args += ["-c:s", "mov_text"]
    if audio_input_index is not None:
        args += ["-metadata:s:a:0", "title=Audio Description"]
        if keep_original_audio:
            args += ["-metadata:s:a:1", "title=Original Audio"]
    if captions_input_index is not None:
        args += ["-metadata:s:s:0", "language=eng"]
    args += ["-movflags", "+faststart", "-shortest", output_path]
    return args


def run_render_job(job_id, ffmpeg_path, video_path, audio_path, captions_path, keep_original_audio, output_path):
    args = build_render_args(ffmpeg_path, video_path, audio_path, captions_path, keep_original_audio, output_path)
    with LOCK:
        JOBS[job_id]["status"] = "running"
        JOBS[job_id]["message"] = "Rendering the accessible video."
    try:
        process = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        with LOCK:
            JOBS[job_id]["process"] = process
        for line in process.stdout:
            with LOCK:
                if JOBS[job_id]["status"] == "cancelled":
                    process.terminate()
                    return
                # FFmpeg's own progress lines aren't parsed into a percentage here (that needs
                # -progress pipe:1 output parsing); we surface the raw last line as a message
                # instead of a fabricated percentage.
                JOBS[job_id]["message"] = line.strip()[-200:] or JOBS[job_id]["message"]
        process.wait()
        with LOCK:
            if JOBS[job_id]["status"] == "cancelled":
                return
            if process.returncode == 0 and os.path.isfile(output_path) and os.path.getsize(output_path) > 0:
                JOBS[job_id]["status"] = "complete"
                JOBS[job_id]["message"] = "Rendering complete."
                JOBS[job_id]["outputPath"] = output_path
            else:
                JOBS[job_id]["status"] = "failed"
                JOBS[job_id]["message"] = "FFmpeg did not produce a usable output file."
    except Exception as error:
        with LOCK:
            JOBS[job_id]["status"] = "failed"
            JOBS[job_id]["message"] = str(error)


class Handler(http.server.BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        pass  # keep the console quiet; nothing here is sensitive but noisy logs aren't useful

    def _send_json(self, payload, status=200):
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_GET(self):
        if self.path == "/health":
            detect_runtimes()
            return self._send_json({"ffmpeg": STATE["ffmpeg"], "ffprobe": STATE["ffprobe"]})

        if self.path.startswith("/render/") and self.path.endswith("/download"):
            job_id = self.path.split("/")[2]
            with LOCK:
                job = JOBS.get(job_id)
            if not job or job.get("status") != "complete":
                return self._send_json({"error": "That render is not ready to download."}, 404)
            output_path = job["outputPath"]
            self.send_response(200)
            self.send_header("Content-Type", "video/mp4")
            self.send_header("Content-Disposition", f'attachment; filename="{os.path.basename(output_path)}"')
            self.send_header("Content-Length", str(os.path.getsize(output_path)))
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            with open(output_path, "rb") as handle:
                shutil.copyfileobj(handle, self.wfile)
            return

        if self.path.startswith("/render/"):
            job_id = self.path.split("/")[2]
            with LOCK:
                job = JOBS.get(job_id)
            if not job:
                return self._send_json({"error": "Unknown job."}, 404)
            return self._send_json({"status": job["status"], "message": job["message"]})

        self._send_json({"error": "Not found."}, 404)

    def do_POST(self):
        length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(length) if length else b""

        if self.path.startswith("/upload/"):
            kind = self.path.split("/")[2]
            if kind not in ("video", "audio", "captions"):
                return self._send_json({"error": "Unsupported asset kind."}, 400)
            asset_id = str(uuid.uuid4())
            extension = {"video": ".mp4", "audio": ".wav", "captions": ".vtt"}[kind]
            path = os.path.join(WORKDIR, asset_id + extension)
            with open(path, "wb") as handle:
                handle.write(body)
            with LOCK:
                ASSETS[asset_id] = path
            return self._send_json({"assetId": asset_id})

        if self.path == "/probe":
            try:
                payload = json.loads(body or b"{}")
                asset_id = payload.get("assetId")
                with LOCK:
                    path = ASSETS.get(asset_id)
                if not path or not os.path.isfile(path):
                    return self._send_json({"error": "Unknown asset."}, 404)
                detect_runtimes()
                return self._send_json(run_ffprobe(path))
            except Exception as error:
                return self._send_json({"error": str(error)}, 500)

        if self.path == "/render":
            try:
                payload = json.loads(body or b"{}")
                detect_runtimes()
                if not STATE["ffmpeg"]["found"]:
                    return self._send_json({"error": "FFmpeg was not detected on this computer."}, 409)
                with LOCK:
                    video_path = ASSETS.get(payload.get("videoAssetId"))
                    audio_path = ASSETS.get(payload.get("describedAudioAssetId")) if payload.get("describedAudioAssetId") else None
                    captions_path = ASSETS.get(payload.get("captionsAssetId")) if payload.get("captionsAssetId") else None
                if not video_path:
                    return self._send_json({"error": "The source video asset was not found. Upload it again."}, 400)
                output_name = "".join(ch for ch in str(payload.get("outputName") or "accessible-video") if ch.isalnum() or ch in "-_") or "accessible-video"
                output_path = os.path.join(WORKDIR, output_name + ".mp4")
                job_id = str(uuid.uuid4())
                with LOCK:
                    JOBS[job_id] = {"status": "queued", "message": "Preparing to render.", "process": None, "outputPath": None}
                thread = threading.Thread(
                    target=run_render_job,
                    args=(job_id, STATE["ffmpeg"]["path"], video_path, audio_path, captions_path, bool(payload.get("keepOriginalAudio")), output_path),
                    daemon=True
                )
                thread.start()
                return self._send_json({"jobId": job_id})
            except Exception as error:
                return self._send_json({"error": str(error)}, 500)

        if self.path.startswith("/render/") and self.path.endswith("/cancel"):
            job_id = self.path.split("/")[2]
            with LOCK:
                job = JOBS.get(job_id)
                if not job:
                    return self._send_json({"error": "Unknown job."}, 404)
                job["status"] = "cancelled"
                process = job.get("process")
            if process:
                try:
                    process.terminate()
                except Exception:
                    pass
            return self._send_json({"status": "cancelled"})

        self._send_json({"error": "Not found."}, 404)


class ThreadingHTTPServer(socketserver.ThreadingMixIn, http.server.HTTPServer):
    daemon_threads = True


def main():
    detect_runtimes()
    server = ThreadingHTTPServer((HOST, PORT), Handler)
    print(f"Media Workflow Assistant local production helper running at http://{HOST}:{PORT}")
    print(f"FFmpeg: {'found at ' + STATE['ffmpeg']['path'] if STATE['ffmpeg']['found'] else 'not found'}")
    print(f"FFprobe: {'found at ' + STATE['ffprobe']['path'] if STATE['ffprobe']['found'] else 'not found'}")
    print("This only accepts connections from this computer. Press Ctrl+C to stop.")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        shutil.rmtree(WORKDIR, ignore_errors=True)


if __name__ == "__main__":
    main()
